version: "3.2"
services:
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "8080:15672"
      - "5672:5672"
    networks:
      - testnet
    restart: 'always'
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
      - RABBITMQ_DEFAULT_USER=mqadmin
      - RABBITMQ_DEFAULT_PASS=Admin123XX_
      - CLUSTERED=true
    deploy:
      resources:
        limits:
          cpus: 1.00
          memory: 512M
  redis1:
    image: redis
    command: redis-server --requirepass Redis123!
    # para usar persistência
    # --appendonly yes
    ports:
      - "6379:6379"
    restart: 'always'
    volumes:
      - $PWD/storage/redis1:/data
    networks:
      - testnet
  #mariadb:
  #  image: "mariadb:10.5"
  #  restart: 'always'
  #  ports:
  #    - "3306:3306"
  #  volumes: 
  #    - "$PWD/storage/mysql:/var/lib/mysql"
  #  environment: 
  #    - MARIADB_ROOT_PASSWORD=Maria123Db!
  #    - MYSQL_USER=admin
  #    - MYSQL_PASSWORD=Ad123min!
  mongodb1:
    networks:
      - testnet
    image: mongo:4.4.7
    restart: 'always'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2020!
      MONGO_INITDB_DATABASE: itau
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./storage/mongodb:/data/db

  mongo-express:
    networks:
      - testnet
    image: mongo-express
    restart: 'always'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb1
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: SenhaDificil54321!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2020!

  #cobranca1:
  #  container_name: itau-cobranca1
  #  networks:
  #    - testnet
  #  build:
  #    context: ./itau-cobranca
  #    dockerfile: Dockerfile
  #  restart: 'always'
  #  ports:
  #    - 9102:9102
  #  environment:
  #    EXTRA_PROPERTIES: "-Dspring.data.mongodb.password=SenhaMuitoDificil123"

networks: 
  testnet:
    driver: bridge